version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USER_ID: ${some_user_name}
      POSTGRES_PASSWORD: ${some_password}
      POSTGRES_DB_NAME: satoshi
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: http://backend:3000/api

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${someusername}
      POSTGRES_PASSWORD: ${somepassword}
      POSTGRES_DB: satoshi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
